name: CI

on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        env:
          TERRAFORM_VERSION: 1.0.9
          TERRAFORM_WRAPPER: false # when enabled JSON output of Terraform Plan is not properly parsed
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: ${{ env.TERRAFORM_WRAPPER }}

      - name: Ensure code is formatted
        run: terraform fmt -diff -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - uses: actions/cache@v2
        name: Cache plugin dir
        with:
         path: ~/.tflint.d/plugins
         key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint
        with:
          tflint_version: v0.29.0

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

      - name: Pull Checkov image
        run: docker pull bridgecrew/checkov:latest

      - name: Scan code with Checkov
        run: |
          docker run \
            --name test-container \
            --tty \
            --rm \
            --volume $(pwd):/tf bridgecrew/checkov:latest \
            --directory /tf \
            --framework terraform \
            --check CKV_AZURE* \
            --soft-fail
