name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  TERRAFORM_VERSION: 1.0.9
  TERRAFORM_WRAPPER: false # when enabled JSON output of Terraform Plan is not properly parsed
  PYTHON_VERSION: 3.8

jobs:
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Checkout bash-scripts repo
        uses: actions/checkout@v2
        with:
          repository: wozorio/bash-scripts
          path: bash-scripts

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: ${{ env.TERRAFORM_WRAPPER }}

      - name: Ensure Terraform code is properly formatted
        run: terraform fmt --recursive -check

      - name: Login to Azure
        run: |
          ./bash-scripts/azure-cli-login.sh \
            ${{ secrets.SUBSCRIPTION_ID }} \
            ${{ secrets.SERVICE_PRINCIPAL_ID }} \
            ${{ secrets.SERVICE_PRINCIPAL_SECRET }} \
            ${{ secrets.TENANT_ID }}

      - name: Terraform Init
        run: |
          ACCESS_KEY=$(az storage account keys list \
            --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
            --query "[0].value" | tr -d '"')

          terraform init -backend-config="access_key=${ACCESS_KEY}"
        env:
          STORAGE_ACCOUNT_NAME: stterraformwozorio

      - name: Terraform Validate
        run: |
          terraform validate

      - name: Verify main Terraform code with Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          check: CKV_AZURE*
          soft_fail: true # disable it to return an error code if there are failed checks

      - name: Verify external Terraform modules with Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .terraform
          framework: terraform
          check: CKV_AZURE*
          soft_fail: true # disable it to return an error code if there are failed checks
