name: "shutdown"

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  shutdown_vms:
    name: Shutdown all virtual machines
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout the bash-scripts repo
        uses: actions/checkout@v2
        with:
          repository: wozorio/bash-scripts

      - name: Login to Azure
        run: |
          ./azure-cli-login.sh ${{ secrets.SUBSCRIPTION_ID }} ${{ secrets.SERVICE_PRINCIPAL_ID }} ${{ secrets.SERVICE_PRINCIPAL_SECRET }} ${{ secrets.TENANT_ID }}

      - name: Shutdown all virtual machines
        run: |
          ./azure-vm-batch-shutdown.sh
