name: Shutdown VMs

on:
  schedule:
    - cron: "0 23 * * *"

defaults:
  run:
    shell: bash

jobs:
  shutdown_vms:
    name: Shutdown all virtual machines
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Shutdown all virtual machines
        run: |
          ./azure-vm-batch-shutdown.sh
