name: Shutdown VMs

on:
  schedule:
    - cron: "0 23 * * *"

defaults:
  run:
    shell: bash

jobs:
  shutdown_vms:
    name: Shutdown all virtual machines
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the bash-scripts repo
        uses: actions/checkout@v3
        with:
          repository: wozorio/bash-scripts

      - name: Login to Azure
        run: |
          ./azure-cli-login.sh \
            ${{ secrets.SUBSCRIPTION_ID }} \
            ${{ secrets.SERVICE_PRINCIPAL_ID }} \
            ${{ secrets.SERVICE_PRINCIPAL_SECRET }} \
            ${{ secrets.TENANT_ID }}

      - name: Shutdown all virtual machines
        run: |
          ./azure-vm-batch-shutdown.sh
