name: Start VMs

on:
  schedule:
    - cron: "0 4 * * *"

defaults:
  run:
    shell: bash

jobs:
  start_vms:
    name: Start all virtual machines
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Start all virtual machines
        run: |
          set -e
          az vm start --ids "$(az vm list --query "[].id" --output tsv)"
