name: 'terraform'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.3

    # Check that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check
    
    # Log in to Azure subscription
    - name: Login to Azure
      run: |
        az login \
          --service-principal \
          --username ${{ secrets.SERVICE_PRINCIPAL_ID }} \
          --password ${{ secrets.SERVICE_PRINCIPAL_SECRET }} \
          --tenant ${{ secrets.TENANT_ID }}

          az account set -s ${{ secrets.SUBSCRIPTION_ID }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: |
        ACCESS_KEY=$(az storage account keys list \
          --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
          --query "[0].value" | tr -d '"')
        
        terraform init -backend-config="access_key=${ACCESS_KEY}"
      env:
        STORAGE_ACCOUNT_NAME: stterraformwozorio

    # Generate an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -var 'admin_password=${{ secrets.ADMIN_PASSWORD }}'
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
        ARM_TENANT_ID: ${{ secrets.TENANT_ID }}

  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: playground
    needs: terraform_plan

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.3

    # Check that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Log in to Azure subscription
    - name: Login to Azure
      run: |
        az login \
          --service-principal \
          --username ${{ secrets.SERVICE_PRINCIPAL_ID }} \
          --password ${{ secrets.SERVICE_PRINCIPAL_SECRET }} \
          --tenant ${{ secrets.TENANT_ID }}

          az account set -s ${{ secrets.SUBSCRIPTION_ID }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: |
        ACCESS_KEY=$(az storage account keys list \
          --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
          --query "[0].value" | tr -d '"')
        
        terraform init -backend-config="access_key=${ACCESS_KEY}"
      env:
        STORAGE_ACCOUNT_NAME: stterraformwozorio

    # On push to master, build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      run: terraform apply -auto-approve -var 'admin_password=${{ secrets.ADMIN_PASSWORD }}'
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
        ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
