name: "terraform"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  TERRAFORM_VERSION: 1.0.9
  TERRAFORM_WRAPPER: false # when enabled JSON output of Terraform Plan is not properly parsed
  PYTHON_VERSION: 3.8

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout bash-scripts repo
        uses: actions/checkout@v2
        with:
          repository: wozorio/bash-scripts
          path: bash-scripts

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: ${{ env.TERRAFORM_WRAPPER }}

      - name: Login to Azure
        run: |
          ./bash-scripts/azure-cli-login.sh \
            ${{ secrets.SUBSCRIPTION_ID }} \
            ${{ secrets.SERVICE_PRINCIPAL_ID }} \
            ${{ secrets.SERVICE_PRINCIPAL_SECRET }} \
            ${{ secrets.TENANT_ID }}

      - name: Terraform Init
        run: |
          ACCESS_KEY=$(az storage account keys list \
            --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
            --query "[0].value" | tr -d '"')

          terraform init -backend-config="access_key=${ACCESS_KEY}"
        env:
          STORAGE_ACCOUNT_NAME: stterraformwozorio

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan -input=false
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}

      - uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: tfplan

      - name: Scan Terraform Plan with Checkov
        run: |
          terraform show -json tfplan | jq '.' > tfplan.json
          docker pull bridgecrew/checkov:latest
          docker run \
            --tty \
            --volume "$(pwd)":/tf bridgecrew/checkov:latest \
            --file /tf/tfplan.json \
            --framework terraform_plan \
            --check CKV_AZURE* \
            --soft-fail

  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: playground
    needs: terraform_plan

    steps:
      - uses: actions/checkout@v2

      - name: Checkout bash-scripts repo
        uses: actions/checkout@v2
        with:
          repository: wozorio/bash-scripts
          path: bash-scripts

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: ${{ env.TERRAFORM_WRAPPER }}

      - name: Login to Azure
        run: |
          ./bash-scripts/azure-cli-login.sh \
            ${{ secrets.SUBSCRIPTION_ID }} \
            ${{ secrets.SERVICE_PRINCIPAL_ID }} \
            ${{ secrets.SERVICE_PRINCIPAL_SECRET }} \
            ${{ secrets.TENANT_ID }}

      - name: Terraform Init
        run: |
          ACCESS_KEY=$(az storage account keys list \
            --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
            --query "[0].value" | tr -d '"')

          terraform init -backend-config="access_key=${ACCESS_KEY}"
        env:
          STORAGE_ACCOUNT_NAME: stterraformwozorio

      - uses: actions/download-artifact@v2
        with:
          name: tfplan

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
