name: "terraform"

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

# Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
defaults:
  run:
    shell: bash

env:
  TERRAFORM_VERSION: 1.0.0

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout terraform-azure repo
        uses: actions/checkout@v2

      - name: Checkout bash-scripts repo
        uses: actions/checkout@v2
        with:
          repository: wozorio/bash-scripts
          path: bash-scripts

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Ensure Terraform code is properly formatted
        run: terraform fmt --recursive -check

      - name: Login to Azure
        run: |
          ./bash-scripts/azure-cli-login.sh \
            ${{ secrets.SUBSCRIPTION_ID }} \
            ${{ secrets.SERVICE_PRINCIPAL_ID }} \
            ${{ secrets.SERVICE_PRINCIPAL_SECRET }} \
            ${{ secrets.TENANT_ID }}

      - name: Terraform Init
        run: |
          ACCESS_KEY=$(az storage account keys list \
            --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
            --query "[0].value" | tr -d '"')

          terraform init -backend-config="access_key=${ACCESS_KEY}"
        env:
          STORAGE_ACCOUNT_NAME: stterraformwozorio

      - name: Terraform Plan
        run: terraform plan
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}

  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: playground
    needs: terraform_plan

    steps:
      - name: Checkout terraform-azure repo
        uses: actions/checkout@v2

      - name: Checkout bash-scripts repo
        uses: actions/checkout@v2
        with:
          repository: wozorio/bash-scripts
          path: bash-scripts

      - name: Ensure Terraform code is properly formatted
        run: terraform fmt --recursive -check

      - name: Login to Azure
        run: |
          ./bash-scripts/azure-cli-login.sh \
            ${{ secrets.SUBSCRIPTION_ID }} \
            ${{ secrets.SERVICE_PRINCIPAL_ID }} \
            ${{ secrets.SERVICE_PRINCIPAL_SECRET }} \
            ${{ secrets.TENANT_ID }}

      - name: Terraform Init
        run: |
          ACCESS_KEY=$(az storage account keys list \
            --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
            --query "[0].value" | tr -d '"')

          terraform init -backend-config="access_key=${ACCESS_KEY}"
        env:
          STORAGE_ACCOUNT_NAME: stterraformwozorio

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
